version: '3.5'
services:
  web_dev:
    build: .
    ports:
      - 5000:5000
    volumes:
      - .:/app
    links:
      - mongo
    environment:
      MONGO_USERNAME: root
      MONGO_PASSWORD: example
  mongo:
    image: mongo
    ports:
      - 27017:27017
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example